package parity

// run_test.go is the HERMETIC parity test: it runs the Go engine over the
// canonical script + the COMMITTED golden bars fixture (testdata/parity/
// bars_canonical.json — the exact wrangled OHLCV the reference Nautilus harness
// consumed) and asserts the engine output field-by-field against the COMMITTED
// Nautilus goldens (orders/positions/account). No Python, no Nautilus, no DB —
// so it runs in the default `go test ./...` and guards against regressions in
// the engine, fill model, accounting and artifact dumper without the heavy
// cross-language gate (that lives behind the `parity` build tag).
//
// The goldens are regenerated by `make parity-nautilus` and copied into
// testdata/ when the reference behavior changes.

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/byjackchen/trade-tms-go/internal/engine"
)

const (
	priceTol = 5e-5
	moneyTol = 0.01
)

func loadJSON(t *testing.T, name string, v any) {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("..", "..", "testdata", "parity", name))
	require.NoError(t, err)
	require.NoError(t, json.Unmarshal(raw, v))
}

// runCanonical runs the Go engine over the committed script + golden bars.
func runCanonical(t *testing.T) *engine.Result {
	t.Helper()
	script, err := LoadScript(filepath.Join("..", "..", "testdata", "parity", "script_canonical.json"))
	require.NoError(t, err)
	feed, err := LoadBarsFeed(filepath.Join("..", "..", "testdata", "parity", "bars_canonical.json"))
	require.NoError(t, err)
	cfg, err := script.EngineConfig()
	require.NoError(t, err)
	eng, err := engine.New(context.Background(), cfg, feed)
	require.NoError(t, err)
	res, err := eng.Run(context.Background())
	require.NoError(t, err)
	return res
}

func TestParityFillsMatchNautilusGolden(t *testing.T) {
	res := runCanonical(t)

	var nau []struct {
		Ticker string `json:"ticker"`
		Side   string `json:"side"`
		Qty    string `json:"qty"`
		Px     string `json:"px"`
		TS     string `json:"ts"`
	}
	loadJSON(t, "nautilus_orders.json", &nau)

	require.Len(t, res.Fills, len(nau), "fill count must match Nautilus")
	for i, want := range nau {
		got := res.Fills[i]
		assert.Equal(t, want.Ticker, got.Symbol, "fill %d ticker", i)
		assert.Equal(t, want.Side, string(got.Side), "fill %d side", i)
		assert.Equal(t, want.Qty, intStr(int64(got.Qty)), "fill %d qty", i)
		assert.InDelta(t, mustFloat(want.Px), got.Price.Float64(), priceTol, "fill %d px", i)
		assert.Equal(t, want.TS[:19], got.TS.UTC().Format("2006-01-02T15:04:05"), "fill %d ts", i)
	}
}

func TestParityPositionsMatchNautilusGolden(t *testing.T) {
	res := runCanonical(t)

	var nau []struct {
		Ticker      string  `json:"ticker"`
		SignedQty   float64 `json:"signed_qty"`
		RealizedPnL float64 `json:"realized_pnl"`
	}
	loadJSON(t, "nautilus_positions.json", &nau)

	byTicker := map[string]struct {
		signed   float64
		realized float64
	}{}
	for _, p := range res.Positions {
		byTicker[p.Symbol] = struct {
			signed   float64
			realized float64
		}{float64(p.SignedQty), p.RealizedPnL.Float64()}
	}
	require.Len(t, byTicker, len(nau))
	for _, want := range nau {
		got, ok := byTicker[want.Ticker]
		require.True(t, ok, "Go missing position for %s", want.Ticker)
		assert.Equal(t, want.SignedQty, got.signed, "%s signed_qty", want.Ticker)
		assert.InDelta(t, want.RealizedPnL, got.realized, moneyTol,
			"%s cumulative realized_pnl", want.Ticker)
	}
}

func TestParityAccountAndEquityMatchNautilusGolden(t *testing.T) {
	res := runCanonical(t)

	// Account: settled balance at each unique timestamp (Nautilus emits more
	// AccountState events than Go — one per instrument at the initial state and
	// an extra at some fills — so compare the LAST balance per unique ts).
	var nauAcct []struct {
		TS         string  `json:"ts"`
		BalanceUSD float64 `json:"balance_usd"`
	}
	loadJSON(t, "nautilus_account.json", &nauAcct)
	nauByTS := lastByTS(func(yield func(string, float64)) {
		for _, p := range nauAcct {
			yield(p.TS[:19], p.BalanceUSD)
		}
	})
	goByTS := lastByTS(func(yield func(string, float64)) {
		for _, p := range res.AccountStates {
			yield(p.TS.UTC().Format("2006-01-02T15:04:05"), p.BalanceUSD.Float64())
		}
	})
	require.Equal(t, len(nauByTS), len(goByTS), "unique account timestamps")
	for ts, nb := range nauByTS {
		gb, ok := goByTS[ts]
		require.True(t, ok, "Go missing account ts %s", ts)
		assert.InDelta(t, nb, gb, moneyTol, "account balance @ %s", ts)
	}

	// Equity: per-bar total equity curve, ts-by-ts.
	var nauEq []struct {
		TS         string  `json:"ts"`
		BalanceUSD float64 `json:"balance_usd"`
	}
	loadJSON(t, "nautilus_equity.json", &nauEq)
	require.Len(t, res.TotalEquityCurve, len(nauEq), "equity curve length")
	for i, want := range nauEq {
		got := res.TotalEquityCurve[i]
		assert.Equal(t, want.TS[:19], got.TS.UTC().Format("2006-01-02T15:04:05"), "equity %d ts", i)
		assert.InDelta(t, want.BalanceUSD, got.Value.Float64(), moneyTol, "equity %d balance", i)
	}

	// Headline: final balance and total PnL.
	assert.InDelta(t, 100661.80, res.FinalBalance.Float64(), moneyTol, "final balance")
	assert.InDelta(t, 661.80, res.TotalPnL.Float64(), moneyTol, "total pnl")
}

// lastByTS collapses a (ts, value) stream to the last value per ts.
func lastByTS(stream func(yield func(string, float64))) map[string]float64 {
	out := map[string]float64{}
	stream(func(ts string, v float64) { out[ts] = v })
	return out
}

func intStr(n int64) string { return strconv.FormatInt(n, 10) }

func mustFloat(s string) float64 {
	f, err := strconv.ParseFloat(s, 64)
	if err != nil {
		panic(err)
	}
	return f
}
