"""Golden vector generator for internal/domain numeric golden tests.

Self-contained (stdlib only, no third-party deps). Regenerate the baseline with:
  python3 gen_golden.py

Output: pyround_golden.txt, one record per line:
  <x.hex()> <round(x,0).hex()> <round(x,2).hex()> <round(x,4).hex()> <quant4>
where quant4 = Decimal(str(x)).quantize(Decimal('0.0001'), ROUND_HALF_EVEN)
(or the literal token OOR when that quantization exceeds the int64 1e-4
fixed-point range). Lines starting with '#' are comments.
"""
import os
import random
from decimal import Decimal, ROUND_HALF_EVEN

random.seed(42)

xs = [
    0.0, -0.0, 1.0, -1.0, 0.5, -0.5, 1.5, 2.5, -2.5, 3.5,
    0.00005, 0.00015, 0.00025, 0.00035, -0.00005, -0.00015,
    2.675, 2.665, 2.685, -2.675, 0.1, 0.2, 0.3, 0.1 + 0.2,
    70.49999999999999, 1e-7, -1e-7, 5e-5, -5e-5, 1e-05,
    123456789.1234, 9e14, -9e14, 0.0001, 0.00009999999999,
    123.456785, 123.456775, 123.45675, 123.45685,
    0.30000000000000004, 1.0000000000000002, 0.062445, 0.062455,
]

# SEPA-style stop products: entry * (1 - pct/100) over a cents price grid.
for c in range(100, 50001, 137):
    e = c / 100.0
    xs += [e, e * 0.925, e * 0.985, e * (1 - 1.5 / 100), e * 1.0001]

# Random uniforms at several magnitudes.
for _ in range(1500):
    xs.append(random.uniform(-1000, 1000))
for _ in range(500):
    xs.append(random.uniform(-1e9, 1e9))
for _ in range(300):
    xs.append(random.uniform(-1, 1))

# Exactly-representable binary grids (produce decimal ties at low digits).
for n in range(-200, 201):
    xs.append(n / 8192)
    xs.append(n / 2**20)
    xs.append(n / 16 + n / 2**13)

MAX_FIXED = Decimal((2**63 - 1)) / Decimal(10000)
MIN_FIXED = Decimal(-(2**63)) / Decimal(10000)
Q = Decimal("0.0001")

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "pyround_golden.txt")
with open(out, "w") as f:
    f.write("# generated by gen_golden.py (python3 stdlib); do not edit\n")
    f.write("# columns: x.hex() round(x,0).hex() round(x,2).hex() round(x,4).hex() quant4\n")
    for x in xs:
        x = float(x)
        if x != x or x in (float("inf"), float("-inf")):
            continue
        r0 = float(round(x, 0))
        r2 = float(round(x, 2))
        r4 = float(round(x, 4))
        q = Decimal(str(x)).quantize(Q, rounding=ROUND_HALF_EVEN)
        qs = str(q) if MIN_FIXED <= q <= MAX_FIXED else "OOR"
        f.write(f"{x.hex()} {r0.hex()} {r2.hex()} {r4.hex()} {qs}\n")
print("wrote", out)
